/**
 * Display names for preview mode, where the keyless catalog carries tickers
 * only. Live mode takes names from the RWA Data API (`underlyingName`).
 * Names for bStocks tickers follow the official "Eligible bStock Tokens" page.
 */
export const COMPANY_NAMES: Record<string, string> = {
  AAOI: "Applied Optoelectronics",
  AAPL: "Apple",
  ALAB: "Astera Labs",
  AMAT: "Applied Materials",
  AMD: "Advanced Micro Devices",
  AMZN: "Amazon",
  ARM: "Arm Holdings",
  ASML: "ASML",
  ASTS: "AST SpaceMobile",
  AVGO: "Broadcom",
  AXTI: "AXT",
  BABA: "Alibaba",
  BE: "Bloom Energy",
  BMNR: "BitMine Immersion Technologies",
  CBRS: "Cerebras",
  COHR: "Coherent",
  COIN: "Coinbase",
  CRCL: "Circle Internet Group",
  CRDO: "Credo Technology",
  CRM: "Salesforce",
  CRWD: "CrowdStrike",
  CRWV: "CoreWeave",
  DELL: "Dell",
  DJT: "Trump Media & Technology Group",
  DRAM: "Roundhill Memory ETF",
  EWY: "iShares MSCI South Korea ETF",
  FLNC: "Fluence Energy",
  GLW: "Corning",
  GME: "GameStop",
  GOOGL: "Alphabet",
  GS: "Goldman Sachs",
  HIMS: "Hims & Hers Health",
  HOOD: "Robinhood",
  IBM: "IBM",
  INTC: "Intel",
  INTW: "GraniteShares 2X Long INTC ETF",
  IREN: "IREN",
  KORU: "South Korea Bull 3X ETF",
  LITE: "Lumentum",
  META: "Meta",
  MRNA: "Moderna",
  MRVL: "Marvell Technology",
  MSFT: "Microsoft",
  MSTR: "Strategy",
  MU: "Micron Technology",
  MUU: "Direxion MU Bull 2X ETF",
  MVLL: "GraniteShares 2X Long MRVL ETF",
  NBIS: "Nebius",
  NFLX: "Netflix",
  NOK: "Nokia",
  NVDA: "NVIDIA",
  ORCL: "Oracle",
  PLTR: "Palantir",
  PYPL: "PayPal",
  QCOM: "Qualcomm",
  QNT: "Quantinuum",
  QQQ: "Invesco QQQ Trust",
  RDDT: "Reddit",
  RKLB: "Rocket Lab",
  SKHY: "SK Hynix",
  SMCI: "Super Micro Computer",
  SMH: "VanEck Semiconductor ETF",
  SNDK: "SanDisk",
  SNXX: "Tradr 2X Long SNDK ETF",
  SOXL: "Semicon Bull 3X ETF",
  SOXS: "Direxion Semiconductor Bear 3X ETF",
  SPCX: "SpaceX",
  SPY: "SPDR S&P 500 ETF",
  SQQQ: "ProShares UltraPro Short QQQ",
  STX: "Seagate",
  TQQQ: "ProShares UltraPro QQQ",
  TSLA: "Tesla",
  TSM: "TSMC",
  USAR: "USA Rare Earth",
  WDC: "Western Digital",
};

/** Search aliases so people can type what they know. */
export const SEARCH_ALIASES: Record<string, string> = {
  google: "GOOGL",
  facebook: "META",
  "s&p": "SPY",
  "s&p 500": "SPY",
  nasdaq: "QQQ",
};

export const FEATURED_TICKERS = ["AAPL", "NVDA", "TSLA", "MSFT", "META", "AMZN", "GOOGL", "SPY", "QQQ", "COIN", "PLTR", "TSM"];
